### ISSUE TITLE
Seeed_Arduino_rpcBLE conflits with other BLE libraries

### ISSUE THREAD

**Issue by rei-vilo** [Seeed-Studio/Seeed_Arduino_rpcBLE#1]
Trying to use the `BLE_scan`example.

The Arduino IDE reports an error because it selects the wrong BLE library.

```
/Users/USER/Documents/Projets/Arduino/libraries/Seeed_Arduino_rpcBLE/examples/BLE_scan/BLE_scan.ino: In function 'void setup()':
BLE_scan:20:16: error: 'init' is not a member of 'BLEDevice'
     BLEDevice::init("");
                ^~~~
BLE_scan:21:27: error: 'getScan' is not a member of 'BLEDevice'
     pBLEScan = BLEDevice::getScan(); //create new scan
                           ^~~~~~~
Multiple libraries were found for "BLEDevice.h"
 Used: /Users/USER/Documents/Projets/Arduino/libraries/ArduinoBLE
 Not used: /Users/USER/Documents/Projets/Arduino/libraries/BLEPeripheral
 Not used: /Users/USER/Documents/Projets/Arduino/libraries/Seeed_Arduino_rpcBLE
```

How to force the use of the **Seeed_Arduino_rpcBLE** library?

**Comment by LynnL4** [comment]
Maybe you need  to remove ArduinoBLE temporary.

**Comment by rei-vilo** [comment]
Indeed, a quick and dirty turnaround consists on removing the two other offending libraries.

However, this is only a patch, not a viable solution.

**Comment by LynnL4** [comment]
It conflicts with Arduino's library， We will change the header file of our library,

**Comment by LynnL4** [comment]
It is logical that we use these header file names, but for some reasons, we need to make some concessions.

**Comment by rei-vilo** [comment]
Great!

**Comment by Pillar1989** [comment]
@rei-vilo  Have you tested the latest software? I think the problem has been solved.

**Comment by rei-vilo** [comment]
That was fast! 

New release works fine, no more conflicts with other BLE libraries.

Actually, the library isn't listed in the **Sketch > Include library > Manage libraries...**. See #2.

Thank you!
