### ISSUE TITLE
Include all Seeed libraries into the Seeed URL json

### ISSUE THREAD

**Issue by rei-vilo** [Seeed-Studio/Seeed_Arduino_rpcBLE#2]
The Arduino IDE features the **Sketch > Include library > Manage libraries...**.

Some libraries from Seeed are listed, but not those related to the radio of the Wio Terminal, _eg._ `Seeed_Arduino_rpcBLE`, `Seeed_Arduino_rpcWiFi`, `Seeed_Arduino_rpcUnified`, `Seeed_Arduino_FreeRTOS`.

<img width="800" alt="Capture 2020-11-07 à 10 59 01" src="https://user-images.githubusercontent.com/951776/98438120-41994f80-20e8-11eb-98c6-51f279021e69.png">

Adding those libraries to the existing URL json would be great

**Comment by LynnL4** [comment]
Sorry, we have no plans to put libraries into Arduino Libraries manger at this time.
