### ISSUE TITLE
Add support for GAP_ADTYPE_SERVICE_DATA

### ISSUE THREAD

**Issue by derekmulcahy** [Seeed-Studio/Seeed_Arduino_rpcBLE#3]
Hi,

I am using some bluetooth temperature/humidity [sensors](https://www.ebay.com/itm/353182934810) which broadcast the readings in the service data. This allows the readings to be received without pairing with the device to the Seeed WIO Terminal.

I hacked this library to copy the service data into the manufacturerData field. This works for me but I was wondering what would be a better way to do it. I am happy to develop and test a solution but I was unsure what would be the best way to change the existing code.

My current hack adds the following to BLEAdvertisedDevice.cpp:349

```
                case GAP_ADTYPE_SERVICE_DATA: {
                    uint8_t data_len = length - 1;      // adtype (-1)
                    memcpy(m_manufacturerData, buffer, data_len);
                    m_manufacturerDataLength = data_len;
                    m_haveManufacturerData = true;
                    break;
                }
```

Cheers,
Derek

**Comment by tyihuang** [comment]
Good job
